version: '3.7'

services:
  postgres:
    container_name: generic_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - red

  redis:
    container_name: generic_redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-123} --databases 5000 --port 6380
    ports:
      - 6380:6380
    command:
      - /bin/sh
      - -c
      - |
        nohup redis-server &
        sleep 5
        echo "adding some default key value"
        redis-cli SET tokens awesome
        echo "Get docker key value"
        redis-cli GET docker
        # this will keep container running
        tail -f /dev/null
    networks:
      - red

networks:
  red: